import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// 1.0 readiness: build an ADR ↔ fixture coverage matrix from the
// `spec_section` field in every fixture's meta.yaml. Two questions
// this answers:
//
// 1. Are there ADRs with NO conformance fixtures? (ADRs that are
//    purely documentation / process don't need fixtures, but
//    semantic ADRs do.)
// 2. Are there fixtures that don't reference any ADR or spec page?
//    (Each fixture should declare what it tests.)
//
// The matrix is also written to `conformance/coverage.md` for
// human review. Adding a new ADR or fixture without updating the
// references will fail this test.

const REPO_ROOT = resolve(fileURLToPath(new URL('../..', import.meta.url)));
const FIXTURE_DIR = join(REPO_ROOT, 'conformance', 'fixtures');
const ADR_DIR = join(REPO_ROOT, 'spec', 'decisions');

// ADRs that are intentionally not covered by fixtures because they
// describe process, audit, or runner protocol — not language
// semantics with observable output.
const INFORMATIONAL_ADRS = new Set([
  '0004', // reference impl coupling audit
  '0005', // dynamic conformance assertions (used by 023)
  '0006', // Stage 2 OOXML conformance protocol
  '0015', // structured error reporting (assertions are in fixtures, but no dedicated semantic fixture)
]);

// Tests used by ADR-0005 dynamic assertion. Counted as covering 0005.
const ADR_0005_FIXTURES = ['023-today-utc-dynamic'];
// Tests used by ADR-0015 structured error code coverage.
const ADR_0015_FIXTURES = ['017', '018', '019', '020', '021', '022', '032', '033', '034', '037', '042', '067', '072', '073', '076', '077', '078', '081', '082', '091'];

describe('spec coverage — ADR ↔ fixture matrix', () => {
  it('every semantic ADR has at least one covering fixture', () => {
    const fixtureRefs = collectFixtureAdrRefs();
    const adrFiles = readdirSync(ADR_DIR)
      .filter((f) => /^\d{4}-.+\.md$/.test(f))
      .filter((f) => f !== '0000-template.md');

    const uncovered: string[] = [];
    for (const f of adrFiles) {
      const id = f.match(/^(\d{4})/)![1]!;
      if (INFORMATIONAL_ADRS.has(id)) continue;
      const refs = fixtureRefs.get(id) ?? [];
      if (refs.length === 0) {
        uncovered.push(f);
      }
    }
    expect(uncovered).toEqual([]);
  });

  it('every fixture declares a spec_section', () => {
    const fixtures = readdirSync(FIXTURE_DIR).filter((entry) =>
      statSync(join(FIXTURE_DIR, entry)).isDirectory(),
    );
    const missing: string[] = [];
    for (const entry of fixtures) {
      const meta = join(FIXTURE_DIR, entry, 'meta.yaml');
      const text = readFileSync(meta, 'utf8');
      if (!/^spec_section:/m.test(text)) missing.push(entry);
    }
    expect(missing).toEqual([]);
  });

  it('writes a coverage matrix to conformance/coverage.md', () => {
    const fixtureRefs = collectFixtureAdrRefs();
    const adrFiles = readdirSync(ADR_DIR)
      .filter((f) => /^\d{4}-.+\.md$/.test(f))
      .filter((f) => f !== '0000-template.md')
      .sort();

    const lines: string[] = [];
    lines.push('# ADR coverage matrix');
    lines.push('');
    lines.push('Auto-generated by `src/__tests__/spec-coverage.test.ts`. Do not edit manually.');
    lines.push('');
    lines.push('| ADR | Title | Covering fixtures |');
    lines.push('|---|---|---|');
    for (const f of adrFiles) {
      const id = f.match(/^(\d{4})/)![1]!;
      const title = readAdrTitle(join(ADR_DIR, f));
      let refs = fixtureRefs.get(id) ?? [];
      if (id === '0005') refs = [...new Set([...refs, ...ADR_0005_FIXTURES])];
      if (id === '0015') refs = [...new Set([...refs, ...ADR_0015_FIXTURES])];
      const cell = refs.length > 0
        ? refs.map((r) => `\`${r.replace(/^0+/, '')}\``).sort().join(', ')
        : INFORMATIONAL_ADRS.has(id) ? '_(informational)_' : '**none**';
      lines.push(`| ${id} | ${title} | ${cell} |`);
    }

    const out = lines.join('\n') + '\n';
    const path = join(REPO_ROOT, 'conformance', 'coverage.md');
    const existing = (() => { try { return readFileSync(path, 'utf8'); } catch { return ''; } })();
    if (existing !== out) {
      writeFileSync(path, out);
    }
    // Always assert the file exists and has content.
    expect(out.length).toBeGreaterThan(100);
  });
});

function collectFixtureAdrRefs(): Map<string, string[]> {
  const refs = new Map<string, string[]>();
  const fixtures = readdirSync(FIXTURE_DIR).filter((entry) =>
    statSync(join(FIXTURE_DIR, entry)).isDirectory(),
  );
  for (const entry of fixtures) {
    const meta = readFileSync(join(FIXTURE_DIR, entry, 'meta.yaml'), 'utf8');
    const m = meta.match(/^spec_section:\s*(.+)$/m);
    if (!m) continue;
    const adrMatches = m[1]!.matchAll(/ADR-(\d{4})/g);
    for (const am of adrMatches) {
      const id = am[1]!;
      if (!refs.has(id)) refs.set(id, []);
      refs.get(id)!.push(entry);
    }
  }
  return refs;
}

function readAdrTitle(path: string): string {
  const text = readFileSync(path, 'utf8');
  const first = text.split('\n')[0]!;
  return first.replace(/^#\s*/, '').replace(/^ADR\s+\d{4}\s*-\s*/, '').trim();
}
