import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // /guides — recipes (flat list, ordered by recipe number).
  guidesSidebar: [
    { type: 'doc', id: 'guides/index', label: 'Overview' },
    { type: 'doc', id: 'guides/getting-started', label: '01 · Getting started' },
    { type: 'doc', id: 'guides/conditional-cells', label: '02 · Conditional cells' },
    { type: 'doc', id: 'guides/aggregates', label: '03 · Aggregates' },
    { type: 'doc', id: 'guides/file-per-group', label: '04 · File per group' },
    { type: 'doc', id: 'guides/sheet-per-group', label: '05 · Sheet per group' },
    { type: 'doc', id: 'guides/runtime-inputs', label: '06 · Runtime inputs' },
    { type: 'doc', id: 'guides/multi-source-join', label: '07 · Multi-source + @join' },
    { type: 'doc', id: 'guides/xlookup', label: '08 · XLOOKUP' },
    { type: 'doc', id: 'guides/sort-and-top', label: '09 · Sort and Top-N' },
    { type: 'doc', id: 'guides/styling-and-branding', label: '10 · Styling and branding' },
    { type: 'doc', id: 'guides/text-formatting', label: '11 · TEXT() formatting' },
    { type: 'doc', id: 'guides/empty-values', label: '12 · Empty values in depth' },
    { type: 'doc', id: 'guides/error-handling', label: '13 · Error handling for hosts' },
    { type: 'doc', id: 'guides/config-values', label: '14 · __config__ as a value dictionary' },
    { type: 'doc', id: 'guides/directive-composition', label: '15 · Composing directives' },
  ],

  // /api — auto-generated from typedoc output. Functions / Interfaces /
  // Types each get a collapsible category.
  apiSidebar: [
    { type: 'doc', id: 'api/index', label: 'API overview' },
    {
      type: 'category',
      label: 'Functions',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api/functions' }],
    },
    {
      type: 'category',
      label: 'Interfaces',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'api/interfaces' }],
    },
    {
      type: 'category',
      label: 'Types',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'api/type-aliases' }],
    },
  ],

  // Unified Docs sidebar — every page reached from the navbar "Docs"
  // dropdown shares this sidebar, so the in-page navigation matches
  // the header IA. Order mirrors the header dropdown exactly. Spec
  // and Conformance are accordion categories that collapse their
  // sub-pages; the other reference docs are flat entries.
  docsSidebar: [
    {
      type: 'category',
      label: 'Spec',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'spec/index', label: 'Spec overview' },
        { type: 'doc', id: 'spec/language', label: 'Language' },
        { type: 'doc', id: 'spec/evaluation', label: 'Evaluation' },
        { type: 'doc', id: 'spec/STABILITY', label: 'Stability' },
        { type: 'doc', id: 'spec/glossary', label: 'Glossary' },
      ],
    },
    { type: 'doc', id: 'PORTERS_GUIDE', label: "Porter's Guide" },
    {
      type: 'category',
      label: 'Conformance',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'conformance/index', label: 'Conformance overview' },
        { type: 'doc', id: 'conformance/DASHBOARD', label: 'Dashboard' },
        { type: 'doc', id: 'conformance/coverage', label: 'Coverage matrix' },
        { type: 'doc', id: 'conformance/runner-protocol', label: 'Runner protocol' },
        { type: 'doc', id: 'conformance/AUTHORING', label: 'Authoring fixtures' },
      ],
    },
    { type: 'doc', id: 'ROADMAP', label: 'Roadmap to 1.0' },
    { type: 'doc', id: 'GOVERNANCE', label: 'Governance' },
    { type: 'doc', id: 'CONTRIBUTING', label: 'Contributing' },
    { type: 'doc', id: 'IMPLEMENTATIONS', label: 'Implementations' },
    { type: 'doc', id: 'RELEASING', label: 'Releasing' },
  ],
};

export default sidebars;
